config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  resources :indices

  root 'indices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/indices_controller.rb
class IndicesController < ApplicationController
  # GET /indices or /indices.json
  def index
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Elm on Rails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'hello_elm' %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
        crossorigin="anonymous">
</head>

<body>
<%= yield %>
</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.name %></td>
        <td><%= pokemon.image %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @pokemon.image %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>